# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/ for more details
#

version: 2
jobs:
  test:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers
    environment:
      - JEKYLL_NO_GITHUB: "true" # Remove Github API integration.
      - JEKYLL_ENV: "production"
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: "true"
      - ELASTICSEARCH_URL: "" # Disable searchyll for test.
    steps:
      - checkout
      - run: which rsync || sudo apt-get install rsync # rsync is needed for swagger build, keep it
      - run: gem install bundler
      - run: make build 
      - run: make test

  # Deploy to production site
  # Note that we need a custom SSH config to let rsync know
  # how to reach the production site.
  build:
    docker:
      - image: circleci/ruby:2.6.0-node-browsers
    environment:
      - JEKYLL_ENV: "production"
      - NOKOGIRI_USE_SYSTEM_LIBRARIES: "true"
    steps:
      - checkout
      - run: npm install .
      - run: gem install bundler
      - run: bundle install
      - run: make include-npm-deps
      - run: mkdir -p ~/.ssh
      - run: echo $SSH_KNOWN_HOSTS | base64 -d >> ~/.ssh/known_hosts
      - run: which rsync || sudo apt-get install rsync
      - run: make download-data
      - run: make build-swagger
      - run: make jekyll-build
      - run: cp -r ./github ./_site/
      - run: make test
      - run: rsync --delete -avP --exclude "Makefile" --rsync-path="sudo -u www-data rsync" ./_site/ circleci@developers.italia.it:/apps/www/developers.italia.it/web/

workflows:
  version: 2
  daily-build-and-deploy:
    triggers:
      - schedule:
          cron: "0 6 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
  on-commit-build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
  on-commit-test:
    jobs:
      - test:
          filters:
            branches:
              ignore:
                - master
