it:
  code: ita
  name: italiano
  t:
    active_lang: lingua attiva
    cookiebar_accept: Accetto
    cookiebar_msg: Questo sito utilizza cookie tecnici, analytics e di terze parti. Proseguendo nella navigazione accetti l’utilizzo dei cookie.
    cookiebar_privacy_policy: Privacy policy
    follow_us: seguici su
    footer_address: Indirizzo
    footer_address_sub: ''
    footer_contacts: Contatti
    footer_contacts_sub: ''
    footer_link_privacy_policy: privacy policy
    footer_link_legal_notes: note legali
    footer_title: ' '
    lang_on_site: sito in italiano
    navigation_menu_label: Menu di navigazione
    navigation_menu_esc: esci dalla navigazione
    scrolltop_label: torna all'inizio dei contenuti
    search_form_label: Vai a progetto...
    search_form_off: disattiva il form di ricerca
    search_form_on: attiva il form di ricerca
    search_form_start: avvia la ricerca
    site_subtitle: La comunità italiana degli sviluppatori di servizi pubblici
    site_title: /developers
    share_msg: condividi
    skiplink_goto_content: vai ai contenuti
    skiplink_goto_navigation: vai alla navigazione del sito
    toggle_menu_label: accedi al menu

    by: di
    on_: "su"
    coming_soon: in arrivo
    news_categories: argomenti
    news_title: Novità
    news_nav_title: Argomenti delle novità

    paginator_previous_page: pagina precedente
    paginator_next_page: pagina successiva
    paginator_page: pagina

    home_hero: La comunità degli sviluppatori che progettano e realizzano i servizi pubblici digitali in Italia
    home_newsletter_title: Iscriviti alla Newsletter
    home_newsletter_placeholder: indirizzo email
    home_newsletter_button: Iscriviti
    home_newsletter_footer: Rimani in contatto per essere informato via via che aggiungeremo nuovi progetti. Non ti assilleremo con troppe email, parola di sviluppatore.
    home_projects_title: Progetti in evidenza
    home_projects_expand: per saperne di più
    home_projects_others: Tutti i progetti
    home_projects_count: progetti in totale
    home_news_title: Novità
    home_news_expand: per saperne di più

    home_tools_title: Strumenti
    home_tools_subtitle: Ci appoggiamo a strumenti già esistenti e molto conosciuti per fornirti le informazioni, il codice e il supporto di cui hai bisogno

    credits_contributors: "Hanno contribuito ai progetti:"

    status_maintainer: Developer Relation, Team Digitale
    status_maintainer: maintainer

    in_collaboration_with: In collaborazione con

    header_link_trasformazione: Piano Triennale
    header_link_developers: Developers
    header_link_design: Designers
    header_link_forum: Forum
    header_link_docs: Docs
    header_link_github: Github

en:
  code: eng
  name: english
  t:
    active_lang: current language
    cookiebar_accept: Accept
    cookiebar_msg: We are using cookies to provide statistics that help us give you the best experience of our site. By continuing to use the site you are agreeing to our use of cookies.
    cookiebar_privacy_policy: Privacy policy
    follow_us: follow us
    footer_address: Address
    footer_address_sub: ''
    footer_contacts: Contacts
    footer_contacts_sub: ''
    footer_link_privacy_policy: privacy policy
    footer_link_legal_notes: terms and conditions
    footer_title: ' '
    lang_on_site: website in english
    navigation_menu_label: Navigation menu
    navigation_menu_esc: exit navigation
    scrolltop_label: back to contents
    search_form_label: Project quicksearch...
    search_form_off: exit search form
    search_form_on: enter search form
    search_form_start: start searching
    site_subtitle: The Italian community of developers of public services
    site_title: /developers
    share_msg: share
    skiplinks_goto_content: go to content
    skiplinks_goto_navigation: go to site navigation
    toggle_menu_label: go to navigation

    by: by
    on_: "on"
    coming_soon: coming soon
    news_categories: tags
    news_title: News
    news_nav_title: Categories

    paginator_previous_page: previous page
    paginator_next_page: next page
    paginator_page: page

    home_hero: A community of developers who design and make Italian digital public services
    home_newsletter_title: Subscribe to our Newlsetter
    home_newsletter_placeholder: email address
    home_newsletter_button: Subscribe
    home_newsletter_footer: Stay in touch to be informed as we add more projects. We're not going to overflow you with too many e-mails; it's a dev-to-dev promise.
    home_projects_title: Highlighted projects
    home_projects_expand: read more
    home_projects_others: All the projects
    home_projects_count: total projects
    home_news_title: News
    home_news_expand: read more

    home_tools_title: Tools
    home_tools_subtitle: We use existing and well_known tools to give you all information, source code and support that you need

    credits_contributors: Project contributors

    status_member_of_board: member of board
    status_maintainer: maintainer

    in_collaboration_with: In collaboration with

    header_link_trasformazione: Piano Triennale
    header_link_developers: Developers
    header_link_design: Designers
    header_link_forum: Forum
    header_link_docs: Docs
    header_link_github: Github
